DiscordBot:
  Token: ""

PostgreSQL:
  Host: "localhost"
  Port: 5432
  User: "postgres"
  Password: "postgres"
  DBName: "billing-db"
  Schema: "public"
  PoolMaxConns: 10

Firebase:
  MainProjectID: "xxxxx"
